services:
  backend:
    container_name: DropIn-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/aungzm/dropin-backend:latest
    environment:
      - DB_URL= #file:../sqlite.db
      - REFRESH_TOKEN_SECRET= 
      - ACCESS_TOKEN_SECRET=
      - DB_TYPE= #sqlite
      - BACKEND_PORT= #5000
      - FRONTEND_URL= #http://localhost:5173
    # ports:
    #   - "5000:5000" # Uncomment if you want to expose the backend port
    networks:
      - dropin-network

  frontend:
    container_name: DropIn-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/aungzm/dropin-frontend:latest
    environment:
      - VITE_BACKEND_URL= # http://localhost:5000
      - VITE_FRONTEND_PORT= #5173
    ports:
      - "5173:80"  # Mapping container port 80 (nginx) to host 5173
    networks:
      - dropin-network

networks:
  dropin-network:
    driver: bridge
